from __future__ import annotations

from datetime import datetime
from typing import Any, Awaitable, Callable, Protocol
from uuid import UUID

from app.application.dtos import Principal, SourceData, ToolCallData

from app.domain.enums import (
    ApplicantType,
    AppointmentStatus,
    ApplicationStatus,
    DeliveryStatus,
    Role,
    ServiceStatus,
)


class AccountCredentialPort(Protocol):
    id: UUID
    username: str
    display_name: str
    password_hash: str
    role: str
    applicant_type: str | None
    active: bool
    token_version: int
    department_id: UUID | None


class BusinessRepositoryPort(Protocol):
    """Persistence gateway consumed by use-case coordinators.

    SQLAlchemy records and sessions remain implementation details of the
    infrastructure adapter. This modular monolith keeps a broad gateway that
    can later be split by aggregate without changing the dependency direction.
    """

    async def create_account(
        self, username: str, password_hash: str, display_name: str,
        applicant_type: ApplicantType, role: Role = Role.CITIZEN,
        department_id: UUID | None = None,
    ) -> AccountCredentialPort: ...
    async def get_account_by_username(self, username: str) -> AccountCredentialPort | None: ...
    async def get_account_record(self, account_id: UUID) -> AccountCredentialPort | None: ...
    async def get_account_view(self, account_id: UUID) -> dict[str, Any]: ...
    async def save_refresh_token(self, account_id: UUID, token: str, expires_at: datetime) -> None: ...
    async def save_refresh_token_if_current(self, account_id: UUID, expected_token_version: int, token: str, expires_at: datetime) -> None: ...
    async def consume_refresh_token(self, token: str) -> AccountCredentialPort | None: ...
    async def revoke_refresh_token(self, token: str) -> None: ...
    async def get_idempotent(self, actor_id: UUID, scope: str, key: str, request_hash: str) -> dict[str, Any] | None: ...
    async def store_idempotent(self, actor_id: UUID, scope: str, key: str, request_hash: str, response: dict[str, Any]) -> dict[str, Any]: ...
    async def execute_idempotent(
        self, actor_id: UUID, scope: str, key: str, request_hash: str,
        operation: Callable[[], Awaitable[dict[str, Any]]],
    ) -> dict[str, Any]: ...
    async def list_services(self, query: str | None = None, include_all: bool = False) -> list[dict[str, Any]]: ...
    async def get_service_bundle(self, service_id: UUID, include_all: bool = False) -> dict[str, Any]: ...
    async def create_department(self, actor_id: UUID, code: str, name: str) -> dict[str, Any]: ...
    async def list_departments(self) -> list[dict[str, Any]]: ...
    async def create_window(self, actor_id: UUID, values: dict[str, Any]) -> dict[str, Any]: ...
    async def list_windows(self, department_id: UUID | None = None) -> list[dict[str, Any]]: ...
    async def create_staff_account(
        self, actor_id: UUID, username: str, password_hash: str,
        display_name: str, department_id: UUID, window_id: UUID | None,
    ) -> dict[str, Any]: ...
    async def list_accounts(self) -> list[dict[str, Any]]: ...
    async def set_account_active(self, actor_id: UUID, account_id: UUID, active: bool) -> dict[str, Any]: ...
    async def create_service(self, actor_id: UUID, values: dict[str, Any]) -> dict[str, Any]: ...
    async def create_service_version(self, actor_id: UUID, service_id: UUID, values: dict[str, Any]) -> dict[str, Any]: ...
    async def transition_service(
        self, actor_id: UUID, service_id: UUID, target: ServiceStatus,
        version_id: UUID | None,
    ) -> dict[str, Any]: ...
    async def list_audits(self, limit: int = 100) -> list[dict[str, Any]]: ...
    async def metrics(self) -> dict[str, int]: ...
    async def get_material_entities(self, service_id: UUID) -> tuple[dict[str, Any], list[Any]]: ...
    async def get_application_case_authorized(self, application_id: UUID, actor_id: UUID, role: Role, department_id: UUID | None = None) -> dict[str, Any]: ...
    async def get_application_view_authorized(self, application_id: UUID, actor_id: UUID, role: Role, department_id: UUID | None = None) -> dict[str, Any]: ...
    async def create_application(self, actor_id: UUID, service_id: UUID, form_data: dict[str, Any]) -> dict[str, Any]: ...
    async def list_applications(self, principal_id: UUID, role: Role, department_id: UUID | None) -> list[dict[str, Any]]: ...
    async def update_application_form(self, application_id: UUID, actor_id: UUID, data: dict[str, Any], expected_version: int) -> dict[str, Any]: ...
    async def preflight_material_upload(self, application_id: UUID, actor_id: UUID, requirement_code: str, content_type: str) -> None: ...
    async def add_material(
        self, application_id: UUID, actor_id: UUID, requirement_code: str,
        original_name: str, object_key: str, content_type: str,
        size_bytes: int, digest: str,
    ) -> dict[str, Any]: ...
    async def get_material_authorized(self, application_id: UUID, material_id: UUID, actor_id: UUID, role: Role, department_id: UUID | None) -> dict[str, Any]: ...
    async def application_submission_context(self, application_id: UUID, actor_id: UUID) -> tuple[Any, dict[str, Any], set[str], list[Any], bool]: ...
    async def submit_application(self, application_id: UUID, actor_id: UUID, expected_version: int) -> dict[str, Any]: ...
    async def transition_application(self, application_id: UUID, actor_id: UUID, role: Role, target: ApplicationStatus, expected_version: int, comment: str | None = None, require_assignee: bool = False) -> dict[str, Any]: ...
    async def list_timeline(self, application_id: UUID, actor_id: UUID, role: Role, department_id: UUID | None) -> list[dict[str, Any]]: ...
    async def list_staff_tasks(self, account_id: UUID, department_id: UUID | None) -> list[dict[str, Any]]: ...
    async def get_review_task_department(self, task_id: UUID) -> UUID: ...
    async def get_application_review_department(self, application_id: UUID) -> UUID: ...
    async def claim_task(self, task_id: UUID, actor_id: UUID, department_id: UUID | None) -> dict[str, Any]: ...
    async def application_requires_payment(self, application_id: UUID) -> bool: ...
    async def list_consultations(self, account_id: UUID) -> list[dict[str, Any]]: ...
    async def create_feedback(self, account_id: UUID, session_id: UUID, rating: int, comment: str | None) -> dict[str, Any]: ...
    async def create_handoff(self, account_id: UUID, session_id: UUID, subject: str, department_id: UUID | None) -> dict[str, Any]: ...
    async def list_handoffs(self, actor_id: UUID, role: Role, department_id: UUID | None) -> list[dict[str, Any]]: ...
    async def add_handoff_message(self, actor_id: UUID, role: Role, department_id: UUID | None, ticket_id: UUID, content: str) -> dict[str, Any]: ...
    async def list_handoff_messages(self, actor_id: UUID, role: Role, department_id: UUID | None, ticket_id: UUID) -> list[dict[str, Any]]: ...
    async def resolve_handoff(self, actor_id: UUID, department_id: UUID | None, ticket_id: UUID) -> dict[str, Any]: ...
    async def cancel_handoff(self, actor_id: UUID, ticket_id: UUID) -> dict[str, Any]: ...
    async def create_appointment(self, account_id: UUID, service_id: UUID, window_id: UUID, slot_start: datetime) -> dict[str, Any]: ...
    async def list_appointments(self, account_id: UUID) -> list[dict[str, Any]]: ...
    async def cancel_appointment(self, account_id: UUID, appointment_id: UUID) -> dict[str, Any]: ...
    async def advance_appointment(self, actor_id: UUID, role: Role, department_id: UUID | None, appointment_id: UUID, target: AppointmentStatus) -> dict[str, Any]: ...
    async def create_payment(self, account_id: UUID, application_id: UUID) -> dict[str, Any]: ...
    async def cancel_payment(self, payment_id: UUID, account_id: UUID) -> dict[str, Any]: ...
    async def mark_payment_pending(self, payment_id: UUID, account_id: UUID) -> dict[str, Any]: ...
    async def update_payment(self, payment_id: UUID, account_id: UUID, outcome: str, provider_reference: str) -> dict[str, Any]: ...
    async def create_verification(self, account_id: UUID, application_id: UUID, expires_at: datetime) -> dict[str, Any]: ...
    async def complete_verification(self, account_id: UUID, verification_id: UUID, outcome: str) -> dict[str, Any]: ...
    async def preflight_delivery(self, account_id: UUID, application_id: UUID) -> dict[str, Any] | None: ...
    async def create_delivery(self, account_id: UUID, application_id: UUID, masked_recipient: str, masked_address: str, provider_reference: str) -> dict[str, Any]: ...
    async def advance_delivery(self, actor_id: UUID, role: Role, department_id: UUID | None, delivery_id: UUID, target: DeliveryStatus) -> dict[str, Any]: ...
    async def cancel_delivery(self, account_id: UUID, delivery_id: UUID) -> dict[str, Any]: ...
    async def create_knowledge_records(
        self, actor_id: UUID, document_id: str, title: str, source: str,
        content: str, object_key: str, chunks: list[str],
    ) -> tuple[UUID, list[dict[str, Any]], bool, str]: ...
    async def finish_knowledge_job(self, job_id: UUID, success: bool, error: str | None = None) -> None: ...
    async def list_active_knowledge_chunks(self) -> list[dict[str, str]]: ...
    async def recover_stale_knowledge_jobs(self, age_seconds: int | None = None) -> int: ...
    async def prepare_knowledge_retry(self, actor_id: UUID, job_id: UUID) -> list[dict[str, Any]]: ...
    async def archive_knowledge(self, actor_id: UUID, job_id: UUID) -> dict[str, Any]: ...


class ObjectStorePort(Protocol):
    materials_bucket: str
    knowledge_bucket: str

    async def ensure_buckets(self) -> None: ...
    async def ping(self) -> None: ...
    async def put_bytes(self, bucket: str, object_key: str, content: bytes, content_type: str) -> None: ...
    async def get_bytes(self, bucket: str, object_key: str) -> bytes: ...
    async def delete(self, bucket: str, object_key: str) -> None: ...


class SmsProviderPort(Protocol):
    async def send_code(self, destination: str, purpose: str) -> dict[str, object]: ...


class PaymentProviderPort(Protocol):
    async def pay(self, outcome: str) -> dict[str, object]: ...


class VerificationProviderPort(Protocol):
    async def verify(self, outcome: str) -> dict[str, object]: ...


class DeliveryProviderPort(Protocol):
    async def create(self) -> dict[str, object]: ...


class VectorIndexPort(Protocol):
    async def index_chunks(self, chunks: list[dict[str, str]]) -> None: ...
    async def activate_chunks(self, chunks: list[dict[str, str]]) -> None: ...
    async def delete_chunks(self, chunk_ids: list[str]) -> None: ...


class ChatPersistencePort(Protocol):
    async def save_user_message(
        self,
        session_id: UUID,
        request_id: UUID,
        message: str,
        owner_account_id: UUID | None = None,
    ) -> None: ...

    async def save_assistant_result(
        self,
        session_id: UUID,
        request_id: UUID,
        answer: str,
        sources: list[SourceData],
        tool_calls: list[ToolCallData],
        cache_hit: bool,
        warnings: list[str],
    ) -> None: ...


class PublicRetrievalCachePort(Protocol):
    async def get(
        self, message: str, public_context_id: str | int | None = None
    ) -> tuple[list[SourceData], list[ToolCallData]] | None: ...

    async def set(
        self,
        message: str,
        sources: list[SourceData],
        tool_calls: list[ToolCallData],
        public_context_id: str | int | None = None,
    ) -> None: ...

    async def invalidate_public(self) -> None: ...


class GovernmentToolRetrievalPort(Protocol):
    async def retrieve(
        self,
        query: str,
        selected_service_id: int | None = None,
        allow_inferred_details: bool = True,
    ) -> tuple[list[SourceData], list[ToolCallData], list[str]]: ...


class KnowledgeRetrievalPort(Protocol):
    async def search(self, query: str, limit: int = 3) -> list[SourceData]: ...


class ChatModelPort(Protocol):
    async def answer(
        self,
        question: str,
        sources: list[SourceData],
        tool_calls: list[ToolCallData],
        request_id: UUID,
    ) -> str: ...


class KnowledgeVectorPort(VectorIndexPort, KnowledgeRetrievalPort, Protocol):
    """Combined search/index capability implemented by the Milvus adapter."""

    pass


class TokenValidationError(ValueError):
    pass


class SecurityPort(Protocol):
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, password: str, encoded: str) -> bool: ...
    def issue_access_token(self, principal: Principal) -> tuple[str, datetime]: ...
    def decode_access_token(self, token: str) -> dict[str, Any]: ...
    def new_refresh_token(self) -> str: ...
    def mask_personal_text(self, value: str) -> str: ...
    def redact_public_text(self, value: str) -> str: ...


class KnowledgeParserPort(Protocol):
    def extract(self, extension: str, content: bytes) -> str: ...
